services:
  - type: web
    name: bde-docuseal-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DOCUSEAL_URL
        value: https://docuseal.co
      - key: DOCUSEAL_API_TOKEN
        sync: false  # Set this in Render dashboard
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: transaction.coordinator.agent@gmail.com
      - key: SMTP_PASSWORD
        value: xmvi xvso zblo oewe
      - key: FROM_EMAIL
        value: transaction.coordinator.agent@gmail.com
      - key: PORT
        value: 8001